version: "3.8"

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  app:
    build: .
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  celery_worker:
    build: .
    command: ["celery", "-A", "tasks.tasks", "worker", "--loglevel=INFO"]
    depends_on:
      - app
    environment:
      - REDIS_HOST=redis

  celery_beat:
    build: .
    command: ["celery", "-A", "tasks.beat", "beat", "--loglevel=INFO"]
    depends_on:
      - app
    environment:
      - REDIS_HOST=redis
